<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pro</string>
	</array>
	<key>name</key>
	<string>Propane</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(define|control)\b</string>
			<key>name</key>
			<string>keyword.control.propane</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.propane</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign.propane</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\{)</string>
			<key>name</key>
			<string>scope.begin.propane</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\})</string>
			<key>name</key>
			<string>scope.end.propane</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$[a-zA-Z]+\$)</string>
			<key>name</key>
			<string>constant.other.propane</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(\/[0-9]+)?)|([0-9]+\.\.[0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.propane</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(in|out|internal|aggregate|tag|maxroutes|longest_path|any|drop|exit|enter|end|start|always|through|avoid|path|reach|valleyfree)\b</string>
			<key>name</key>
			<string>support.function.propane</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(in|out)\b</string>
			<key>name</key>
			<string>support.variable.magic.propane</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>AS numbers</string>
			<key>match</key>
			<string>\b(as[0-9]+)\b</string>
			<key>name</key>
			<string>constant.language.boolean.propane</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.propane</string>
	<key>uuid</key>
	<string>C69CCFE2-6EE0-43D2-883E-E352A9C96738</string>
</dict>
</plist>
